### ISSUE TITLE
Home page has 'Recommendations' button highlighted 

### ISSUE THREAD

**Issue by shadycloud** [Smart-Recommendations/Smart-Recommendations#35]
![Screenshot_20240312_144637_Smart Recommendations](https://github.com/Smart-Recommendations/Smart-Recommendations/assets/13189052/452d7194-5cfc-4f5a-9312-cc2801254eb5)
![Screenshot_20240312_144633_Smart Recommendations](https://github.com/Smart-Recommendations/Smart-Recommendations/assets/13189052/83183c8c-c543-4e82-9fe4-08d594858a94)

**Comment by shadycloud** [comment]
There was some talk about getting rid of some areas of the app... /perhaps this issue will be cleared up by the conclusion of such.

**Comment by 22acmsu** [comment]
No longer relevant with rewrite.
